config/routes.rb
GXSchedules::Application.routes.draw do

  devise_for :users, path: 'admin'

  scope :format => true, :constraints => { :format => 'json' } do
    get '/clubs', to: "clubs#index", defaults: { format: 'json' }
    get '/categories', to: 'categories#index', defaults: { format: 'json' }
    get '/tracks', to: 'tracks#index', defaults: { format: 'json' }
  end
  
  resources :tracks, only: [ :show ]
  resources :categories, only: [ :show ]
  resources :gx_classes, path: "classes", only: [ :index, :show ]

  scope "/:club_id", as: :club, constraints: { club_id: /[A-Z]{2,3}/ } do
    resources :gx_classes, path: "classes", only: [ :index  ] do
      get "/:id", to: "instances#show"
    end
    resources :studios, :instructors, only: [ :index, :show ]
    get "/", to: "clubs#show"
  end
  
  scope :admin do
    resources :gx_classes, path: "classes", except: [ :show, :index ]
    get '/classes/:id', to: redirect('/classes/%{id}')
    get '/classes', to: redirect('/classes')
    resources :clubs, except: [ :show, :index ]
    scope "/:club_id", as: :club, constraints: { club_id: /[A-Z]{2,3}/ } do
      get "/", to: "club#show"
      resources :gx_class_sets, path: "class_sets", except: [ :index ] do
        resources :instances, except: [ :new ]
      end
      resources :studios, :instructors
      resources :users
    end
    resources :tracks, :categories
    get "/", to: "admin#index"
  end

  root 'clubs#index'

end

app/models/instance.rb
class Instance < ActiveRecord::Base
  belongs_to :gx_class_set
  has_one :gx_class, through: :gx_class_set
  has_many :reservations
  belongs_to :instructor
  belongs_to :studio
  
  def get_at var
    var.downcase!
    if ['instructor','club','studio'].include? var
      case var
        when 'instructor'
          instructor || gx_class_set.instructor
        when 'club'
          club || gx_class_set.club
        when 'studio'
          studio || gx_class_set.studio
      end
    else
      self[var] || gx_class_set[var]
    end
  end
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  before_action :set_instance, only: [:show, :edit, :update, :destroy]
  before_action :set_club

  # GET /instances
  # def index
  #   @instances = Instance.all
  # end
  # 
  # # GET /instances/1
  # def show
  # end

  # GET /instances/1/edit
  def edit
    @instance.attributes.each do |k,v|
      if v.nil?
        @instance[k]=@instance.gx_class_set[k]
      end
    end
    @instance.start_time = @instance.start_time.to_s(:time)
    @instance.end_time   = @instance.end_time.to_s(:time)
  end

  # PATCH/PUT /instances/1
  def update
    @params = instance_params
    puts @params
    @params.delete_if{|k,v|
      puts [k,v]
      if ['start_time','end_time'].include? k
        v == @instance.gx_class_set[k].to_s(:time)
      else
        v == @instance.gx_class_set[k] || (Float(v) && Float(v) == @instance.gx_class_set[k])
      end
    }
    puts @params
    if @instance.update(@params)
      redirect_to club_path(@club, date: @instance.effective_date), notice: 'Instance was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /instances/1
  def destroy
    @instance.destroy
    redirect_to club_path(@club, date: @instance.effective_date), notice: 'Instance was successfully destroyed.'
  end

  private
    def set_club
      @club = Club.find_by(cAbbrv: params[:club_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_instance
      @instance = Instance.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def instance_params
      params.require(:instance).permit(:gx_class_set_id,:effective_date,:studio_id,:instructor_id,:start_time,:end_time,:canceled)
    end
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/views/instances/_form.html.haml
= form_for [@club, @instance.gx_class_set, @instance] do |f|
  - if @instance.errors.any?
    #error_explanation
      %h2= "#{pluralize(@instance.errors.count, "error")} prohibited this instance from being saved:"
      %ul
        - @instance.errors.full_messages.each do |msg|
          %li= msg
  %h1
    Class:
    =link_to @instance.gx_class.name, @instance.gx_class
  %h2
    Date:
    = @instance.effective_date.strftime("%-m.%-d.%Y")
  = f.label :instructor_id do
    %strong Instructor:
    =f.select :instructor_id, Instructor.joins(:clubs).where(clubs: { id: @club.id }).order('last_name ASC, first_name ASC').map{|x| [x.last_name.nil? || x.last_name=="" ? "• #{x.first_name}" : "#{x.last_name}, #{x.first_name}",x.id] }, { include_blank: '– Instructor –' }, { size: 8 }
  = f.label :studio_id do
    %strong Studio:
    =f.select :studio_id, Studio.joins(:club).where(clubs: { id: @club.id }).order(:name).map{|x| [x.name, x.id]}, { include_blank: '– Studio –' }, { size: 4 }
  = f.label :start_time, class: 'show' do
    %strong Start Time:
    =f.text_field :start_time, type: 'time', placeholder: 'Start Time'
  = f.label :end_time, class: 'show' do
    %strong End Time:
    =f.text_field :end_time, type: 'time', placeholder: 'End Time'
  = f.label :canceled, class: 'checkbox' do
    =f.check_box :canceled
    %strong Canceled
  .actions
    = f.submit 'Save'

app/views/instances/_listitem.html.haml
%li.class{class: i.canceled? ? "canceled" : ""}
  %h3.name= link_to i.gx_class.name, i.gx_class
  %p.instructor{class: i.instructor_id.nil? ? "" : "changed" }= link_to "#{i.get_at('instructor').first_name} #{i.get_at('instructor').last_name}", [@club,i.get_at('instructor')]
  %p.info
    %span.studio{class: i.studio_id.nil? ? "" : "changed" }= link_to i.get_at('studio').name + (/studio/i === i.get_at('studio').name ? "" : " Studio"), [@club,i.get_at('studio')]
    %span.time{class: i.start_time.nil? || i.end_time.nil? ? "" : "changed" }= i.get_at('start_time').strftime(i.get_at('start_time').hour < 12 && i.get_at('end_time').hour > 12 ? "%-I:%M%P" : "%-I:%M") + " – " + i.get_at('end_time').strftime("%-I:%M%P")
  - if current_user.try(:admin?)
    %p.admin
      =link_to "Change", edit_club_gx_class_set_instance_path(@club,i.gx_class_set,i)
      =link_to "Update", edit_club_gx_class_set_path(@club,i.gx_class_set)
      =link_to (i.canceled? ? "Reinstate" : "Cancel"), club_gx_class_set_instance_path(@club,i.gx_class,i, instance: { canceled: !i.canceled? }), confirm: "Are you sure you wish to #{i.canceled? ? 'reinstate' : 'canceled'} #{i.gx_class.name} on #{i.effective_date.strftime("%-m.%-d.%Y")}?", method: :patch

app/views/instances/edit.html.haml
%h1 Editing instance

= render 'form'

= link_to 'Back', :back

app/views/instances/new.html.haml
%h1 New instance

= render 'form'

= link_to 'Back', club_path(@club)