config/routes.rb
GXSchedules::Application.routes.draw do

  devise_for :users, path: 'admin'

  scope :format => true, :constraints => { :format => 'json' } do
    get '/clubs', to: "clubs#index", defaults: { format: 'json' }
    get '/categories', to: 'categories#index', defaults: { format: 'json' }
    get '/tracks', to: 'tracks#index', defaults: { format: 'json' }
  end
  
  resources :tracks, only: [ :show ]
  resources :categories, only: [ :show ]
  resources :gx_classes, path: "classes", only: [ :index, :show ]

  scope "/:club_id", as: :club, constraints: { club_id: /[A-Z]{2,3}/ } do
    resources :gx_classes, path: "classes", only: [ :index  ] do
      get "/:id", to: "instances#show"
    end
    resources :studios, :instructors, only: [ :index, :show ]
    get "/", to: "clubs#show"
  end
  
  scope :admin do
    resources :gx_classes, path: "classes", except: [ :show, :index ]
    get '/classes/:id', to: redirect('/classes/%{id}')
    get '/classes', to: redirect('/classes')
    resources :clubs, except: [ :show, :index ]
    scope "/:club_id", as: :club, constraints: { club_id: /[A-Z]{2,3}/ } do
      get "/", to: "club#show"
      resources :gx_class_sets, path: "class_sets", except: [ :index ] do
        resources :instances, except: [ :new ]
      end
      resources :studios, :instructors
      resources :users
    end
    resources :tracks, :categories
    get "/", to: "admin#index"
  end

  root 'clubs#index'

end

app/models/gx_class_set.rb
class GxClassSet < ActiveRecord::Base  
  LEVELS = [['1-3','All Levels'],['1','Beginner'],['2','Intermediate'],['3','Advanced'],['1-2','Beginner to Intermediate'],['2-3','Intermediate to Advanced']]

  belongs_to :gx_class
  belongs_to :club
  belongs_to :instructor
  belongs_to :studio
  has_many :instances
  
  validates :club_id, :gx_class_id, :studio_id, :instructor_id, :start_date, :repeat_times, :start_time, :end_time, presence: true
  validates_associated :club, :gx_class, :studio, :instructor
  validates :level, inclusion: 0..(LEVELS.count-1)
#  validates :start_time
  
  after_create :create_child_instances

  def self.level_short
    LEVELS[level][0]
  end

  def self.level_long
    LEVELS[level][1]
  end
  
  def repeat_times
    @repeat_times ||= instances.empty? ? 1 : instances.count
  end
  def repeat_times=(value)
    attribute_will_change!('repeat_times') if repeat_times != value
    @repeat_times = value
  end

  private
  def create_child_instances
    (self.repeat_times.nil? ? 1 : repeat_times.to_i).times do |x|
      instances.create(effective_date: start_date + x.weeks)
    end
  end
end

app/controllers/gx_class_sets_controller.rb
class GxClassSetsController < ApplicationController
  before_action :set_club
  before_action :set_gx_class_set, only: [:show, :edit, :update, :destroy]

  # GET /gx_class_sets
  #def index
  #  @gx_class_sets = GxClassSet.all
  #end

  # GET /gx_class_sets/1
  def show
  end

  # GET /gx_class_sets/new
  def new
    @gx_class_set = GxClassSet.new
    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  # GET /gx_class_sets/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  # POST /gx_class_sets
  def create
    @gx_class_set = GxClassSet.new(gx_class_set_params)

    if @gx_class_set.save
      redirect_to @club, notice: 'Class set was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /gx_class_sets/1
  def update
    if @gx_class_set.update(gx_class_set_params)
      redirect_to @club, notice: 'Class set was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /gx_class_sets/1
  def destroy
    @gx_class_set.destroy
    redirect_to gx_class_sets_url, notice: 'Class set was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gx_class_set
      @gx_class_set = GxClassSet.find(params[:id])
    end
    
    def set_club
      @club = Club.find_by(cAbbrv: params[:club_id])
    end

    # Only allow a trusted parameter "white list" through.
    def gx_class_set_params
      params.require(:gx_class_set).permit(:gx_class_id, :studio_id, :instructor_id, :level, :repeat_times, :start_date, :start_time, :end_time, :reservable, :paid_class_csi_id, :reserve_max, :club_id)
    end
end

app/helpers/gx_class_sets_helper.rb
module GxClassSetsHelper
end

app/views/gx_class_sets/_form.html.haml
= form_for [@club,@gx_class_set] do |f|
  - if @gx_class_set.errors.any?
    #error_explanation
      %h2= "#{pluralize(@gx_class_set.errors.count, "error")} prohibited this gx_class_set from being saved:"
      %ul
        - @gx_class_set.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :club_id, value: @club.id
  = f.label :gx_class_id do
    %strong Class:
    =f.select :gx_class_id, GxClass.all.order(:name).map{|x| [x.name,x.id]}, { include_blank: '– Class –' }, { size: 8 }
  = f.label :instructor_id do
    %strong Instructor:
    =f.select :instructor_id, Instructor.joins(:clubs).where(clubs: { id: @club.id }).order('last_name ASC, first_name ASC').map{|x| [x.last_name.nil? || x.last_name=="" ? "• #{x.first_name}" : "#{x.last_name}, #{x.first_name}",x.id] }, { include_blank: '– Instructor –' }, { size: 8 }
  = f.label :level do
    %strong Level:
    =f.select :level, GxClassSet::LEVELS.each_with_index.map{|v,k| ["#{v[1]} (#{v[0]})",k] }, {}, { size: 4 }
  = f.label :studio_id do
    %strong Studio:
    =f.select :studio_id, Studio.joins(:club).where(clubs: { id: @club.id }).order(:name).map{|x| [x.name, x.id]}, { include_blank: '– Studio –' }, { size: 4 }
  = f.label :start_date, class: 'show date' do
    %strong Start Date:
    =f.date_select :start_date
  = f.label :repeat_times, class: 'show' do
    %strong Instances:
    =f.text_field :repeat_times, type: 'number', placeholder: 'Instances', min: 1, max: 52
  = f.label :start_time, class: 'show' do
    %strong Start Time:
    =f.text_field :start_time, type: 'time', placeholder: 'Start Time'
  = f.label :end_time, class: 'show' do
    %strong End Time:
    =f.text_field :end_time, type: 'time', placeholder: 'End Time'
  .reservations
    = f.label :reservable, class: 'checkbox' do
      =f.check_box :reservable
      %strong Reservable
    = f.label :paid_class_csi_id do
      %strong CSI ID (paid):
      =f.text_field :paid_class_csi_id, placeholder: 'CSI ID (paid)'
    = f.label :reserve_max do
      %strong Capacity (unpaid):
      =f.text_field :reserve_max, type: 'number', placeholder: 'Capacity (unpaid)'

  .actions
    = f.submit @gx_class_set.new_record? ? "Create Schedule" : "Update Schedule"

app/views/gx_class_sets/edit.html.haml
%h1 Editing gx_class_set

= render 'form'

= link_to 'Show', [@club,@gx_class_set]
= link_to 'Back', club_path

app/views/gx_class_sets/index.html.haml
%h1 Listing gx_class_sets

%table
  %tr
    %th
    %th
    %th

  - @gx_class_sets.each do |gx_class_set|
    %tr
      %td= link_to 'Show', [gx_class_set.club, gx_class_set]
      %td= link_to 'Edit', edit_club_gx_class_set_path(gx_class_set)
      %td= link_to 'Destroy', [gx_class_set.club, gx_class_set], :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Gx class set', new_club_gx_class_set_path

app/views/gx_class_sets/new.html.haml
- content_for :title, "New Class Schedule"

= render 'form'

= link_to 'Back', club_path

app/views/gx_class_sets/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_club_gx_class_set_path(@gx_class_set.club,@gx_class_set)
\|
= link_to 'Back', club_path(@club)